bin/copy, bin/pasta: remove `/tmp/clipboard`
I recommend reviewing this with whitespace changes disabled.

I don't think I've ever used this, so let's remove it.

diff --git a/home/bin/bin/copy b/home/bin/bin/copy
--- a/home/bin/bin/copy
+++ b/home/bin/bin/copy
@@ -3,16 +3,12 @@ set -e
 set -u
 
 if hash pbcopy 2>/dev/null; then
-  exec pbcopy
+	exec pbcopy
 elif hash xclip 2>/dev/null; then
-  exec xclip -selection clipboard
+	exec xclip -selection clipboard
 elif hash putclip 2>/dev/null; then
-  exec putclip
+	exec putclip
 else
-  rm -f /tmp/clipboard 2> /dev/null
-  if [ $# -eq 0 ]; then
-    cat > /tmp/clipboard
-  else
-    cat "$1" > /tmp/clipboard
-  fi
+	echo 'cannot find a copy program' >&2
+	exit 1
 fi
diff --git a/home/bin/bin/pasta b/home/bin/bin/pasta
--- a/home/bin/bin/pasta
+++ b/home/bin/bin/pasta
@@ -3,11 +3,10 @@ set -e
 set -u
 
 if hash pbpaste 2>/dev/null; then
-  exec pbpaste
+	exec pbpaste
 elif hash xclip 2>/dev/null; then
-  exec xclip -selection clipboard -o
-elif [[ -e /tmp/clipboard ]]; then
-  exec cat /tmp/clipboard
+	exec xclip -selection clipboard -o
 else
-  echo ''
+	echo 'cannot find a paste program' >&2
+	exit 1
 fi
