bin/snippets: ensure that snippet doesn't contain `..`
This would be me path-traversing myself. But let's close the hole
anyway.

diff --git a/home/bin/bin/snippets b/home/bin/bin/snippets
--- a/home/bin/bin/snippets
+++ b/home/bin/bin/snippets
@@ -4,16 +4,21 @@ set -u
 set -o pipefail
 
 if [[ $# -ne 1 ]]; then
-  echo 'must pass exactly 1 argument' 1>&2
-  exit 1
+	echo 'must pass exactly 1 argument' 1>&2
+	exit 1
+fi
+
+if [[ "$1" == *".."* ]]; then
+	echo 'invalid snippet name' 1>&2
+	exit 1
 fi
 
 XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
 path="$XDG_CONFIG_HOME/evanhahn-snippets/$1"
 
 die() {
-  echo "no snippet found at $path" 1>&2
-  exit 1
+	echo "no snippet found at $path" 1>&2
+	exit 1
 }
 
 cat "$path" 2>/dev/null || die
