move serveit into its own script, flesh it out

diff --git a/resources/bin/serveit b/resources/bin/serveit
--- a/resources/bin/serveit
+++ b/resources/bin/serveit
@@ -7,4 +7,15 @@ if [ $# -eq 1 ]; then
   port="$1"
 fi
 
-python -m SimpleHTTPServer "$port"
+if hash php 2>/dev/null; then
+  php -S "localhost:$port"
+elif hash ruby 2>/dev/null; then
+  ruby -run -e httpd . -p "$port"
+elif hash python 2>/dev/null; then
+  # TODO: python 3 support
+  # python -m http.server "$port"
+  python -m SimpleHTTPServer "$port"
+else
+  echo 'unable to start HTTP server'
+  exit 1
+fi
